default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: personal_journal_development

test:
  <<: *default
  host: localhost
  database: personal_journal_test

production:
  <<: *default
  url: <%= ENV.fetch("POSTGRESQL_URL", "") %>
